FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
COPY target/getting-started-1.0.0-SNAPSHOT.jar gettingstarted.jar
EXPOSE 8181
ENTRYPOINT exec java $JAVA_OPTS -jar gettingstarted.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar gettingstarted.jar
